[tool.pytest.ini_options]
addopts = "-q -ra"
testpaths = ["tests"]
pythonpath = ["."]

[tool.ruff]
target-version = "py313"
line-length = 100

[tool.ruff.lint]
select = ["E","F","I","C90"]         # C90: cyclomatic complexity (軽いガード)
ignore = []

[tool.mypy]
python_version = "3.13"
strict = true
